x-cu-base: &cu
  image: cshas/cu
  build:
    context: ../
    dockerfile: docker/Dockerfile.cu
  ports:
    - "1600:1600"

x-sensor-base: &sensor
  image: cshas/sensor
  build:
    context: ../
    dockerfile: docker/Dockerfile.sensor
  stdin_open: true
  tty: true

x-keypad-base: &keypad
  image: cshas/keypad
  build:
    context: ../
    dockerfile: docker/Dockerfile.keypad
  stdin_open: true
  tty: true
  
x-siren-base: &siren
  image: cshas/siren
  build:
    context: ../
    dockerfile: docker/Dockerfile.siren
    
services:
  listener:
    image: cshas/listener
    build:
      context: ../
      dockerfile: docker/Dockerfile.listener
    environment:
      - CLUSTER_IP=listener
      - CLUSTER_PORT=1500
      - SEED_PORT_1600_TCP_ADDR=cu
  
  cu:
    <<: *cu
    environment:
      - CLUSTER_IP=cu
      - CLUSTER_PORT=1600
      - SEED_PORT_1600_TCP_ADDR=cu
      - CORRECT_PIN=1234

  sensor1:
    <<: *sensor
    environment:
      - CLUSTER_IP=sensor1
      - CLUSTER_PORT=1701
      - SEED_PORT_1600_TCP_ADDR=cu
      - SENSOR_ID=sensor1
      - ZONES=bedroom,livingroom
      - SENSOR_TYPE=motion

  sensor2:
    <<: *sensor
    environment:
      - CLUSTER_IP=sensor2
      - CLUSTER_PORT=1702
      - SEED_PORT_1600_TCP_ADDR=cu
      - SENSOR_ID=sensor2
      - ZONES=kitchen
      - SENSOR_TYPE=barrier

  keypad:
    <<: *keypad
    environment:
      - CLUSTER_IP=keypad
      - CLUSTER_PORT=1800
      - SEED_PORT_1600_TCP_ADDR=cu
      
  siren:
    <<: *siren
    environment:
      - CLUSTER_IP=siren
      - CLUSTER_PORT=1900
      - SEED_PORT_1600_TCP_ADDR=cu
